"""empty message

Revision ID: 0ebad306caf8
Revises: 
Create Date: 2019-08-26 15:34:01.849149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ebad306caf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('pw_hash', sa.String(length=256), nullable=False),
    sa.Column('dev_id', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dev_id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('coco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('img', sa.String(length=32), nullable=False),
    sa.Column('proxy', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('light', sa.Boolean(), nullable=False),
    sa.Column('lightColor', sa.String(length=12), nullable=True),
    sa.Column('lightBrightness', sa.Float(), nullable=True),
    sa.Column('cred', sa.String(length=256), nullable=False),
    sa.Column('timeConnection', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proxy')
    )
    op.create_table('routine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=20), nullable=False),
    sa.Column('days', sa.String(length=100), nullable=False),
    sa.Column('times', sa.String(length=64), nullable=False),
    sa.Column('coco_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coco_id'], ['coco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routine')
    op.drop_table('coco')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
