"""empty message

Revision ID: 4c5c037488a9
Revises: 0ebad306caf8
Create Date: 2019-08-30 16:23:10.362590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5c037488a9'
down_revision = '0ebad306caf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coco', sa.Column('deviceType', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coco', 'deviceType')
    # ### end Alembic commands ###
